title: Add-On Docs
email: cyber@code.horse
description: >-
  Unofficial documentation for Minecraft Bedrock Add-Ons.
baseurl: ""
url: "https://bedrock.nerd.horse"
twitter_username: CyberPon3

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

permalink: pretty

defaults:
- scope:
    path: ""
  values:
    layout: "default"